# Generated by Django 3.1.6 on 2021-04-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField()),
                ('business_pid', models.TextField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_compliance_rating', models.IntegerField(default=5)),
                ('capacity_limit', models.IntegerField(default=0)),
                ('indoor_dining', models.BooleanField(default=False)),
                ('outdoor_dining', models.BooleanField(default=False)),
                ('curbside_pickup', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('body', models.TextField(default='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changed.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changed.businessinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
