# Generated by Django 3.1.6 on 2021-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='average_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='published_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='published_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
