# Generated by Django 3.1.6 on 2021-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_addr',
            field=models.TextField(default='no address'),
            preserve_default=False,
        ),
    ]
