# Generated by Django 3.1.6 on 2021-03-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0003_auto_20210326_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessComments',
        ),
    ]
