# Generated by Django 3.1.6 on 2021-04-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0003_auto_20210412_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 11, 51, 23, 706324)),
        ),
    ]
