# Generated by Django 3.1.6 on 2021-05-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0004_auto_20210418_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 43, 33, 167330)),
        ),
    ]
