# Generated by Django 3.1.6 on 2021-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0004_delete_businesscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_id',
            field=models.IntegerField(default=0),
        ),
    ]
