# Generated by Django 3.1.6 on 2021-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0004_businessinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='capacity_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='curbside_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='indoor_dining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='outdoor_dining',
            field=models.BooleanField(default=False),
        ),
    ]
