# Generated by Django 3.1.6 on 2021-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0005_business_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_id',
        ),
        migrations.AddField(
            model_name='business',
            name='business_addr',
            field=models.TextField(default='no address'),
        ),
    ]
