# Generated by Django 3.1.6 on 2021-03-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0006_auto_20210329_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_addr',
            field=models.TextField(default='', unique=True),
        ),
    ]
