# Generated by Django 3.1.6 on 2021-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0007_auto_20210329_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_addr',
            field=models.TextField(default='No address'),
        ),
    ]
